"""Add CityAnalysis for cached city scans

Written by hand rather than autogenerated: app.py calls db.create_all() at
import, so the table already exists in any database the autogenerate step can
reach, and alembic therefore reports no changes. Deployments that run
migrations instead of create_all (Render/Postgres) still need this.

Revision ID: c3f81a92b7d4
Revises: a2c91d7e4f10
Create Date: 2026-09-27
"""
import sqlalchemy as sa
from alembic import op

revision = "c3f81a92b7d4"
down_revision = "a2c91d7e4f10"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "city_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("cell_size_m", sa.Integer(), nullable=False, server_default="1000"),
        sa.Column("tier", sa.String(length=20), nullable=False, server_default="estimated"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="complete"),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("cells_json", sa.JSON(), nullable=False),
        sa.Column("sources_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_city_analysis_name", "city_analysis", ["name"])
    op.create_index("ix_city_analysis_country_code", "city_analysis", ["country_code"])
    op.create_index("ix_city_analysis_expires_at", "city_analysis", ["expires_at"])


def downgrade():
    op.drop_index("ix_city_analysis_expires_at", table_name="city_analysis")
    op.drop_index("ix_city_analysis_country_code", table_name="city_analysis")
    op.drop_index("ix_city_analysis_name", table_name="city_analysis")
    op.drop_table("city_analysis")
